import type { EqBand, SourceMode } from './types'

export type EqProfile = {
  id: string
  mode: SourceMode
  label: string
  shortLabel: string
  measurementLabel: string
  description: string
  goal: string
  lowCutEnabled: boolean
  lowCutFrequency: number
  eqBands: EqBand[]
  bandNotes: string[]
  targetCenter: number[]
  targetRange: number[]
  preflight: string[]
  optimizationSteps: string[]
  cautions: string[]
}

const band = (
  name: string,
  frequency: number,
  gain: number,
  q: number,
  filterType: EqBand['filterType'] = 'PEQ',
): EqBand => ({ name, frequency, gain, q, filterType })

export const EQ_PROFILES: EqProfile[] = [
  {
    id: 'preacher-gooseneck',
    mode: 'preacher',
    label: '설교자 · 구즈넥/강대상',
    shortLabel: '구즈넥',
    measurementLabel: '설교 음성',
    description: '강대상 반사, 진동, 콤 필터링과 저중역 뭉침을 먼저 확인하는 설교자용 시작점입니다.',
    goal: '말의 뼈대는 유지하면서 200–350Hz의 뭉침과 5–10kHz의 피로를 줄이고 자음 전달력을 확보합니다.',
    lowCutEnabled: true,
    lowCutFrequency: 120,
    eqBands: [
      band('Low', 250, -3, 1.6),
      band('Low Mid', 650, -2, 3.5),
      band('High Mid', 2800, 1, 0.8),
      band('High', 7000, -1.5, 4),
    ],
    bandNotes: ['강대상·근접효과 저중역', 'Boxy·Nasal 공진 후보', '자음 명료도 보강 후보', '치찰음이 확인될 때만 감쇠'],
    targetCenter: [22, 34, 43, 49, 54, 61, 59, 45],
    targetRange: [8, 8, 9, 9, 9, 10, 10, 10],
    preflight: ['마이크 캡슐과 입의 거리 일정', '강대상 진동·케이블 접촉음 확인', '입력 Peak와 클리핑을 EQ보다 먼저 확인'],
    optimizationSteps: ['Low Cut을 천천히 올리며 음성 뼈대 손실 확인', '200–350Hz를 넓게 소폭 감쇠', '500–900Hz 공진은 좁게 탐색', '2–4kHz는 명료도와 피로도를 함께 비교'],
    cautions: ['성별만으로 Low Cut을 확정하지 않습니다.', '강대상 반사 문제를 채널 EQ만으로 해결했다고 판단하지 않습니다.'],
  },
  {
    id: 'preacher-headset',
    mode: 'preacher',
    label: '설교자 · 이어셋/헤드셋',
    shortLabel: '이어셋',
    measurementLabel: '설교 음성',
    description: '볼 옆 위치에서 발생하는 고역 손실과 흉성 저중역 누적을 함께 점검합니다.',
    goal: '150–300Hz의 웅웅거림을 줄이고 3–8kHz의 말 윤곽을 자연스럽게 복원합니다.',
    lowCutEnabled: true,
    lowCutFrequency: 100,
    eqBands: [
      band('Low', 200, -3.5, 1.7),
      band('Low Mid', 600, -1.5, 3),
      band('High Mid', 3500, 1.5, 0.8),
      band('High', 9000, 1, 0.7, 'HighShelf'),
    ],
    bandNotes: ['흉성·근접 저역 정리', '좁은 비음 후보', '발음 윤곽 복원', '공기감은 노이즈와 함께 확인'],
    targetCenter: [24, 37, 44, 50, 56, 63, 63, 52],
    targetRange: [8, 8, 9, 9, 9, 10, 10, 10],
    preflight: ['캡슐 위치가 입꼬리에서 일정한지 확인', '케이블 마찰음과 송신기 Gain 확인', '고역 Boost 전 치찰음과 히스 확인'],
    optimizationSteps: ['150–250Hz를 먼저 정리', '3–5kHz를 넓고 작게 보강', '8kHz 이상은 Shelf로 미세 조정', '같은 문장으로 A/B 재측정'],
    cautions: ['헤드셋 모델별 주파수 응답 차이가 큽니다.', '고역을 올리기 전에 송신기·수신기 노이즈를 확인합니다.'],
  },
  {
    id: 'preacher-handheld',
    mode: 'preacher',
    label: '설교자 · 핸드헬드',
    shortLabel: '핸드헬드',
    measurementLabel: '설교 음성',
    description: '입과 마이크 거리 변화에 따른 근접효과와 파지법 변화를 중심으로 봅니다.',
    goal: '거리 변화에도 저역이 과도하게 출렁이지 않도록 하고 중고역 전달력을 안정화합니다.',
    lowCutEnabled: true,
    lowCutFrequency: 100,
    eqBands: [
      band('Low', 180, -2.5, 1.5),
      band('Low Mid', 600, -1.5, 2.8),
      band('High Mid', 3000, 1, 0.9),
      band('High', 7000, -1, 3.5),
    ],
    bandNotes: ['거리 변화에 따른 근접효과', '비음·답답함 후보', '명료도 보강 후보', '치찰음이 있을 때만 감쇠'],
    targetCenter: [25, 38, 44, 50, 55, 62, 60, 47],
    targetRange: [9, 9, 9, 9, 9, 10, 10, 10],
    preflight: ['마이크와 입의 거리 5–10cm 유지', '그릴을 손으로 감싸지 않는지 확인', '가장 큰 발성에서 Peak 확인'],
    optimizationSteps: ['Low Cut과 150–250Hz를 함께 비교', '파지법이 바뀌어도 같은 톤인지 확인', '2–4kHz는 +1dB 수준부터 시작', '객석 여러 위치에서 재확인'],
    cautions: ['거리가 계속 바뀌면 고정 EQ보다 사용 습관 교정이 먼저입니다.', 'Feedback은 실제 Monitor/Main 출력 경로를 확인합니다.'],
  },
  {
    id: 'vocal-balanced',
    mode: 'vocal',
    label: '보컬 · 밸런스 시작점',
    shortLabel: '밸런스',
    measurementLabel: '보컬',
    description: '보컬의 몸통, 존재감, 치찰음과 공기감을 균형 있게 비교하는 중립 시작점입니다.',
    goal: '저중역의 혼탁함을 줄이면서 2–5kHz의 존재감과 8kHz 이상의 개방감을 과하지 않게 확보합니다.',
    lowCutEnabled: true,
    lowCutFrequency: 100,
    eqBands: [
      band('Low', 250, -2, 1.5),
      band('Low Mid', 700, -1, 2.5),
      band('High Mid', 3500, 1.5, 0.8),
      band('High', 10000, 1, 0.7, 'HighShelf'),
    ],
    bandNotes: ['저중역 혼탁함', 'Nasal·Boxy 후보', 'Presence·가사 전달력', 'Air·개방감'],
    targetCenter: [24, 38, 45, 51, 57, 64, 65, 55],
    targetRange: [9, 9, 9, 9, 10, 10, 10, 11],
    preflight: ['가장 큰 고음에서 Peak 확인', '컴프레서·De-Esser 상태 기록', '반주와 함께 마스킹 여부 확인'],
    optimizationSteps: ['Cut-before-boost로 저중역부터 정리', '2–5kHz는 반주 안에서 판단', '치찰음은 EQ와 De-Esser를 비교', '10kHz 이상은 노이즈와 함께 확인'],
    cautions: ['보컬 음역과 마이크에 따라 시작점이 크게 달라집니다.', '솔로 청취와 전체 믹스 청취를 모두 수행합니다.'],
  },
  {
    id: 'vocal-muddy',
    mode: 'vocal',
    label: '보컬 · 먹먹함 정리',
    shortLabel: '먹먹함',
    measurementLabel: '보컬',
    description: '100–400Hz가 과도하고 가사가 뒤로 물러나는 보컬을 위한 보수적인 정리 시작점입니다.',
    goal: '보컬의 두께를 잃지 않으면서 200–350Hz의 혼탁함과 500–900Hz의 박스톤을 줄입니다.',
    lowCutEnabled: true,
    lowCutFrequency: 120,
    eqBands: [
      band('Low', 250, -4, 1.5),
      band('Low Mid', 700, -2, 3),
      band('High Mid', 3200, 1, 0.9),
      band('High', 9000, 0.5, 0.8, 'HighShelf'),
    ],
    bandNotes: ['Muddy·Boomy 핵심 후보', 'Boxy·Nasal 후보', '명료도 소폭 복원', 'Air는 최소한으로'],
    targetCenter: [20, 32, 40, 48, 55, 63, 64, 52],
    targetRange: [8, 8, 9, 9, 10, 10, 10, 11],
    preflight: ['마이크 거리와 근접효과 확인', '반주 저역과 보컬 마스킹 확인', 'Low Cut 전후 음성 뼈대 비교'],
    optimizationSteps: ['200–300Hz를 넓게 감쇠', '500–900Hz는 좁게 탐색', '고역 Boost는 저중역 정리 후 판단', 'A/B에서 가사 전달력과 두께를 함께 평가'],
    cautions: ['저중역을 많이 깎으면 보컬이 얇고 멀어질 수 있습니다.', '공간 잔향 문제를 채널 EQ만으로 해결하지 않습니다.'],
  },
  {
    id: 'vocal-sibilant',
    mode: 'vocal',
    label: '보컬 · 치찰음 제어',
    shortLabel: '치찰음',
    measurementLabel: '보컬',
    description: '5–10kHz의 치찰음과 귀 피로를 줄이되 보컬의 개방감을 보존하는 시작점입니다.',
    goal: '치찰음이 실제로 발생하는 좁은 지점만 제어하고 2–5kHz의 전달력은 유지합니다.',
    lowCutEnabled: true,
    lowCutFrequency: 100,
    eqBands: [
      band('Low', 250, -2, 1.6),
      band('Low Mid', 800, -1, 2.8),
      band('High Mid', 3000, 0, 1),
      band('High', 7000, -3, 4.5),
    ],
    bandNotes: ['저중역 기본 정리', 'Nasal 후보', 'Presence 유지', 'Sibilance 좁은 감쇠'],
    targetCenter: [23, 37, 44, 51, 58, 64, 61, 47],
    targetRange: [9, 9, 9, 9, 10, 10, 10, 10],
    preflight: ['치찰음이 특정 발음에서 반복되는지 확인', '마이크 축과 입의 각도 확인', 'De-Esser 사용 여부 기록'],
    optimizationSteps: ['6–9kHz를 좁게 탐색', '깊은 고정 Cut과 De-Esser를 비교', 'Presence 대역은 불필요하게 깎지 않음', '전체 믹스에서 개방감 손실 확인'],
    cautions: ['치찰음 대역은 화자와 마이크마다 다릅니다.', '좁은 Q의 큰 Cut은 발음이 흐려질 수 있습니다.'],
  },
  {
    id: 'instrument-kick',
    mode: 'instrument',
    label: '악기 · 킥 드럼',
    shortLabel: '킥',
    measurementLabel: '킥 드럼',
    description: '저역 펀치, 100–200Hz의 부밍, 300–500Hz의 박스톤과 3–6kHz 어택을 구분합니다.',
    goal: '저역 펀치를 유지하면서 부밍과 박스톤을 줄이고 필요한 만큼 어택을 확보합니다.',
    lowCutEnabled: true,
    lowCutFrequency: 35,
    eqBands: [
      band('Low', 55, 2, 1.2),
      band('Low Mid', 150, -3, 2.5),
      band('High Mid', 400, -3, 1.5),
      band('High', 4500, 2, 1),
    ],
    bandNotes: ['Fundamental·Punch', 'Boom control', 'Boxiness', 'Attack·Click'],
    targetCenter: [62, 55, 40, 36, 38, 46, 58, 40],
    targetRange: [11, 11, 10, 10, 10, 10, 11, 11],
    preflight: ['마이크 위치와 드럼 튜닝 확인', '게이트·컴프레서 상태 기록', '베이스 기타와 저역 마스킹 확인'],
    optimizationSteps: ['50–80Hz의 펀치와 헤드룸 비교', '100–200Hz 부밍을 좁게 정리', '300–500Hz 박스톤 감쇠', '3–6kHz 어택은 장르에 맞게 조절'],
    cautions: ['스피커 시스템이 재생할 수 없는 초저역 Boost를 피합니다.', '솔로보다 베이스와 함께 판단합니다.'],
  },
  {
    id: 'instrument-snare',
    mode: 'instrument',
    label: '악기 · 스네어',
    shortLabel: '스네어',
    measurementLabel: '스네어',
    description: 'Body, Boxiness, Ringing과 Attack을 분리해 조정하는 시작점입니다.',
    goal: '스네어의 몸통과 어택을 살리면서 코맹맹이 소리와 링을 제한합니다.',
    lowCutEnabled: true,
    lowCutFrequency: 90,
    eqBands: [
      band('Low', 180, 2, 1.2),
      band('Low Mid', 700, -3, 4),
      band('High Mid', 2500, 1.5, 1),
      band('High', 8000, 1, 0.8, 'HighShelf'),
    ],
    bandNotes: ['Body', 'Ring·Nasal 후보', 'Attack', 'Brightness'],
    targetCenter: [24, 42, 58, 46, 44, 55, 64, 58],
    targetRange: [10, 10, 11, 10, 10, 11, 11, 11],
    preflight: ['스네어 튜닝과 댐핑 상태 확인', 'Bottom mic 위상 확인', 'Ringing이 일정한 주파수인지 확인'],
    optimizationSteps: ['80–100Hz 아래 Rumble 정리', 'Body를 100–250Hz에서 확인', 'Ring은 좁은 Q로 소폭 Cut', '2–8kHz 어택과 거칠음을 비교'],
    cautions: ['-10dB 같은 강한 Surgical Cut은 최후 수단입니다.', '드럼 자체 튜닝 문제를 EQ로 숨기지 않습니다.'],
  },
  {
    id: 'instrument-bass',
    mode: 'instrument',
    label: '악기 · 베이스',
    shortLabel: '베이스',
    measurementLabel: '베이스',
    description: '저역 기반, 100–200Hz 부밍, 400Hz–1kHz 뭉침과 2–4kHz의 픽 노이즈를 구분합니다.',
    goal: '킥과 충돌하지 않는 저역 기반을 만들고 필요한 음정 정의만 남깁니다.',
    lowCutEnabled: true,
    lowCutFrequency: 40,
    eqBands: [
      band('Low', 80, 1, 1),
      band('Low Mid', 180, -2, 1.8),
      band('High Mid', 700, -2, 2),
      band('High', 3000, -1, 2),
    ],
    bandNotes: ['Fundamental', 'Boom control', 'Mid congestion', 'Pick·Slap noise'],
    targetCenter: [60, 58, 50, 44, 46, 50, 44, 30],
    targetRange: [11, 11, 10, 10, 10, 10, 10, 10],
    preflight: ['DI·앰프 마이킹 경로 확인', '킥과 저역 역할 분담 확인', '컴프레서와 새츄레이션 상태 기록'],
    optimizationSteps: ['60–100Hz 기반 확인', '100–200Hz 부밍 감쇠', '400Hz–1kHz 음정 정의와 뭉침 비교', '2–4kHz는 연주 방식에 맞게 조절'],
    cautions: ['저역 Boost는 헤드룸을 빠르게 소모합니다.', '작은 스피커에서는 고조파 정보가 더 중요할 수 있습니다.'],
  },
  {
    id: 'instrument-acoustic-guitar',
    mode: 'instrument',
    label: '악기 · 어쿠스틱 기타',
    shortLabel: '어쿠스틱',
    measurementLabel: '어쿠스틱 기타',
    description: '저역 Rumble, 100–400Hz 부밍, 피킹 선명도와 10kHz 이상의 Air를 구분합니다.',
    goal: '저역 마스킹을 줄이고 스트럼의 선명도와 자연스러운 공기감을 확보합니다.',
    lowCutEnabled: true,
    lowCutFrequency: 120,
    eqBands: [
      band('Low', 180, -2.5, 1.7),
      band('Low Mid', 350, -2, 2.2),
      band('High Mid', 3500, 1, 1),
      band('High', 11000, 1, 0.8, 'HighShelf'),
    ],
    bandNotes: ['Boom control', 'Body congestion', 'Pick definition', 'Air'],
    targetCenter: [22, 35, 43, 49, 52, 58, 62, 55],
    targetRange: [9, 9, 10, 10, 10, 10, 11, 11],
    preflight: ['픽업과 마이크 입력 경로 확인', '바디 공진과 룸 반사 구분', '보컬·피아노와 마스킹 확인'],
    optimizationSteps: ['Low Cut으로 저역 공간 확보', '100–400Hz 부밍 정리', '2–5kHz 피킹 선명도 확인', '10kHz 이상 Shelf는 히스와 비교'],
    cautions: ['바디감을 과도하게 제거하지 않습니다.', '픽업 특유의 Piezo harshness는 2–5kHz에서 별도 확인합니다.'],
  },
  {
    id: 'instrument-electric-guitar',
    mode: 'instrument',
    label: '악기 · 일렉 기타',
    shortLabel: '일렉 기타',
    measurementLabel: '일렉 기타',
    description: '200–400Hz의 부밍, 중역 존재감과 5–7kHz 이상의 Fizz를 구분합니다.',
    goal: '중역 캐릭터를 유지하면서 저중역 뭉침과 고역 Fizz를 줄여 믹스 안에 안착시킵니다.',
    lowCutEnabled: true,
    lowCutFrequency: 80,
    eqBands: [
      band('Low', 300, -2.5, 1.8),
      band('Low Mid', 800, -1, 2),
      band('High Mid', 2500, 1, 1.1),
      band('High', 6500, -2, 0.9, 'HighShelf'),
    ],
    bandNotes: ['Boom control', 'Mid congestion', 'Presence', 'Fizz control'],
    targetCenter: [20, 30, 42, 55, 63, 64, 54, 32],
    targetRange: [9, 9, 10, 10, 11, 11, 11, 10],
    preflight: ['앰프·캐비닛·마이크 위치 확인', '다른 기타와 중역 역할 분담', '게인·디스토션 양 확인'],
    optimizationSteps: ['200–400Hz 부밍 정리', '700Hz–2kHz 캐릭터 보존', '2–4kHz 존재감 조절', '5–7kHz 이상 Fizz를 넓게 감쇠'],
    cautions: ['High Shelf 감쇠는 실제 LPF와 다르게 동작합니다.', '기타 톤은 솔로보다 전체 믹스에서 판단합니다.'],
  },
  {
    id: 'instrument-piano',
    mode: 'instrument',
    label: '악기 · 피아노/건반',
    shortLabel: '피아노',
    measurementLabel: '피아노',
    description: '베이스와의 저역 마스킹, 3–5kHz의 해머 어택과 고역 개방감을 균형화합니다.',
    goal: '밴드 믹스에서 저역 공간을 확보하고 코드와 어택이 또렷하게 들리도록 합니다.',
    lowCutEnabled: true,
    lowCutFrequency: 80,
    eqBands: [
      band('Low', 160, -2, 1.5),
      band('Low Mid', 500, -1, 2),
      band('High Mid', 4000, 1.5, 1),
      band('High', 10000, 1, 0.8, 'HighShelf'),
    ],
    bandNotes: ['Bass masking control', 'Mid congestion', 'Hammer attack', 'Air'],
    targetCenter: [30, 43, 50, 52, 55, 60, 64, 57],
    targetRange: [10, 10, 10, 10, 10, 11, 11, 11],
    preflight: ['스테레오 입력 위상·패닝 확인', '베이스·킥과 저역 역할 분담', '음색 프리셋 자체의 EQ 확인'],
    optimizationSteps: ['100–200Hz 마스킹 정리', '400Hz–1kHz 중역 밀도 확인', '3–5kHz 해머 어택 보강', '고역은 보컬 치찰음과 충돌 여부 확인'],
    cautions: ['피아노 솔로와 밴드 믹스의 목표가 다릅니다.', '스테레오 악기의 한쪽 채널만 측정하지 않습니다.'],
  },
  {
    id: 'instrument-synth',
    mode: 'instrument',
    label: '악기 · 신스/패드',
    shortLabel: '신스/패드',
    measurementLabel: '신스/패드',
    description: '넓은 스펙트럼이 저역과 보컬 공간을 덮지 않도록 역할 중심으로 정리합니다.',
    goal: '필요하지 않은 저역을 비우고 보컬과 핵심 악기의 공간을 남긴 채 분위기를 유지합니다.',
    lowCutEnabled: true,
    lowCutFrequency: 150,
    eqBands: [
      band('Low', 250, -2, 1.4),
      band('Low Mid', 700, -1, 1.8),
      band('High Mid', 3000, 0, 1),
      band('High', 10000, 0.5, 0.8, 'HighShelf'),
    ],
    bandNotes: ['Low-end clearance', 'Mid masking control', 'Presence reserve', 'Air texture'],
    targetCenter: [16, 24, 38, 48, 54, 57, 56, 51],
    targetRange: [9, 9, 10, 10, 10, 11, 11, 11],
    preflight: ['패치 자체의 저역·모듈레이션 확인', '베이스·피아노와 역할 분담', '스테레오 폭과 모노 호환 확인'],
    optimizationSteps: ['150Hz 이하를 역할에 따라 정리', '250Hz–1kHz 마스킹 확인', '보컬 Presence 대역을 비움', '고역 질감은 전체 믹스에서 판단'],
    cautions: ['저역을 담당하는 신스에는 동일 HPF를 적용하지 않습니다.', '패치가 바뀌면 프로필을 다시 검증합니다.'],
  },
  {
    id: 'instrument-strings',
    mode: 'instrument',
    label: '악기 · 스트링',
    shortLabel: '스트링',
    measurementLabel: '스트링',
    description: '200–300Hz의 통울림과 7–10kHz의 Bow noise·Air를 구분합니다.',
    goal: '따뜻한 몸통을 유지하면서 둔탁함과 거친 활 소리를 제어합니다.',
    lowCutEnabled: true,
    lowCutFrequency: 100,
    eqBands: [
      band('Low', 250, -2, 1.6),
      band('Low Mid', 700, -1, 2),
      band('High Mid', 4000, 1, 1),
      band('High', 8500, 0, 1, 'HighShelf'),
    ],
    bandNotes: ['Body muddiness', 'Mid density', 'Definition', 'Bow noise·Air'],
    targetCenter: [24, 37, 45, 52, 57, 60, 61, 53],
    targetRange: [9, 9, 10, 10, 10, 11, 11, 11],
    preflight: ['실제 스트링·샘플 소스 구분', '마이크 거리·룸 반사 확인', '보컬과 2–5kHz 마스킹 확인'],
    optimizationSteps: ['200–300Hz 둔탁함 정리', '중역 밀도 유지', '3–5kHz 정의 보강', '7–10kHz는 거칠음과 Air를 양방향 비교'],
    cautions: ['고역을 무조건 Boost하지 않습니다.', '앙상블 크기에 따라 저중역 누적량이 달라집니다.'],
  },
  {
    id: 'instrument-choir',
    mode: 'instrument',
    label: '악기/소스 · 성가대',
    shortLabel: '성가대',
    measurementLabel: '성가대',
    description: '다수 음성이 겹치며 커지는 250–400Hz와 가사 전달을 위한 3–5kHz를 관리합니다.',
    goal: '성가대의 규모감은 유지하면서 저중역 누적을 줄이고 가사 전달력을 확보합니다.',
    lowCutEnabled: true,
    lowCutFrequency: 100,
    eqBands: [
      band('Low', 300, -3, 1.5),
      band('Low Mid', 700, -1, 2.5),
      band('High Mid', 4000, 1.5, 0.8),
      band('High', 8000, 0, 1, 'HighShelf'),
    ],
    bandNotes: ['다수 음성 저중역 누적', '중역 혼잡', '가사 전달력', 'Air·치찰음 균형'],
    targetCenter: [20, 34, 42, 50, 56, 62, 63, 52],
    targetRange: [9, 9, 10, 10, 10, 11, 11, 11],
    preflight: ['마이크 수와 간격·위상 확인', '무대 모니터 유입 확인', '합창 인원과 편성 기록'],
    optimizationSteps: ['100Hz 아래 Rumble 정리', '250–400Hz 누적을 넓게 감쇠', '3–5kHz 가사 전달력 보강', '여러 마이크 합산 후 다시 측정'],
    cautions: ['개별 마이크 EQ보다 전체 합산을 함께 봅니다.', '피드백 마진은 모니터·메인 출력 경로별로 확인합니다.'],
  },
]

export const DEFAULT_PROFILE_ID = 'preacher-gooseneck'

export function getEqProfile(id: string): EqProfile {
  return EQ_PROFILES.find((profile) => profile.id === id) ?? EQ_PROFILES[0]
}

export function getProfilesForMode(mode: SourceMode): EqProfile[] {
  return EQ_PROFILES.filter((profile) => profile.mode === mode)
}

export function cloneProfileBands(profile: EqProfile): EqBand[] {
  return profile.eqBands.map((item) => ({ ...item }))
}

export const MODE_LABELS: Record<SourceMode, string> = {
  preacher: '설교자',
  vocal: '보컬',
  instrument: '악기',
}
